### ISSUE TITLE
如何单独测试一个视频？

### ISSUE THREAD

**Issue by DWCTOD** [MCG-NJU/DDM#1]
大佬您好，想请教一下，如果想要测试一个单独的视频应该要用哪个代码？谢谢啦

**Comment by JackyTown** [comment]
You can refer to GUIDE.md for detailed instructions.

```
python tools/generate_pickle.py $TEST_DATA_ROOT --split test
```

让 testing set 对应的 pickle 中只有一个视频即可。

**Comment by DWCTOD** [comment]
收到，谢谢大佬，之前看了这个 You can refer to GUIDE.md for detailed instructions.，但是第三步往下的好像相关代码没有 https://github.com/MCG-NJU/DDM/blob/main/GUIDE.md#3-generate-submission-file-and-evaluateval ，不过可能应该可以通过这个来调整 https://github.com/StanLei52/GEBD/tree/main/PC
我再试一试，再次感谢大佬

**Comment by JackyTown** [comment]
代码是有的哈：
https://github.com/MCG-NJU/DDM/blob/main/tools/post_process.py
https://github.com/MCG-NJU/DDM/blob/main/tools/eval.py
