### ISSUE TITLE
视频切割10s ，使用ffmpeg么

### ISSUE THREAD

**Issue by songxia928** [MCG-NJU/DDM#4]
您好，请教一个问题！

这里（https://github.com/MCG-NJU/DDM/blob/main/GUIDE.md）的  ”1-c“ 步，分割出10s的视频片段，是用 ffmpeg么

命令比如： ffmpeg     -ss 00:01:38    -i input.mp4     -t 00:00:10   -vcodec copy  -acodec copy     output.mp4

**Comment by JackyTown** [comment]
可以的

**Comment by zhanglu-cst** [comment]
请问切割的视频都是从0秒开始的吗，还是看保存的文件名的，例如，'air_drumming/tdpHu69TU5w_000004_000014.mp4'，就是从4秒到14秒？
